create table keyword_history
(
    id         bigint generated by default as identity,
    created_at timestamp,
    updated_at timestamp,
    count      bigint,
    keyword    varchar(255),
    primary key (id)
);